[ADD] travis/cfg/travis_run_pylint_pr.cfg
Elico-Corp/maintainer-quality-tools pull request #2
Opened 2017-01-22 11:02 UTC by victormartinelicocorp

This could work but need to be tested.
Note that the code is arbitrary choosed as to indentify message
not really exist by Pylint.
	modified:   travis/cfg/travis_run_pylint_pr.cfg

2017-01-22 11:02 UTC, victormartinelicocorp commented
To be Tested.

But please review @elicoidal @seb-elico

2017-01-22 11:10 UTC, seb-elico requested changes

2017-01-22 11:10 UTC, seb-elico commented on travis/cfg/travis_run_pylint_pr.cfg
> +manifest_required_support="support@elico-corp.com"
@victormartinelicocorp I'm not sure this is enough. You mean the check of value of the key is triggered by some naming convention? I would assume that somewhere, there's something to trigger this check on this field. IMO we should check all occurrences of `manifest_required_author` to see if there's a trigger and replicate that mechanism. If no other occurrence, then it means you're right about the automatic trigger based on name convention.

2018-08-28 08:32 UTC, lonelysun commented
@seb-elico 
 `manifest-required-author - C8101` is necessary ？
This still make Szmig repo travis red, 

> __manifest__.py:5: [C8101(manifest-required-author), ] One of the following authors must be present in manifest: 'Odoo Community Association (OCA)'

cc @victormartinelicocorp

2018-09-05 09:43 UTC, victormartinelicocorp commented
I would close this PR and rebase our repository fork which is out to date with OCA one
`This branch is 12 commits ahead, 28 commits behind OCA:master. `
what you think @seb-elico @lonelysun ?

cc @elicoidal

2018-11-02 02:41 UTC, closed without merging